name: apiverve_hmac
description: HMAC Generator creates Hash-based Message Authentication Codes for data integrity and authentication. Supports SHA-256, SHA-384, SHA-512, SHA-1, and MD5 algorithms.
version: 1.1.14
homepage: https://apiverve.com/marketplace/hmac?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/hmac-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
